# waylock.toml

# Note: all fields are optional. If omitted a default value will be used.

# Command to run on authentication failure. Executed with `sh -c <COMMAND>`.
fail_command = "echo Failed unlock attempt!"

# Set the font for the shown text
# font="JetBrainsMono"

# Set maximal restarts/second if the process crashes. Default is 5. To endlessly restart, set the value to 0.
max_restarts = 5

[colors]
# Specify the initial color of the lock screen.
init_color = 0x002b36
# Specify the color of the lock screen after input is received.
input_color = 0x586e75
# Specify the color of the lock screen on authentication failure.
fail_color = 0xdc322f
# Specify the background color for the lock
bg_color = 0x111115
# Specify the text color for the UI
text_color = 0xffffdd
